### PR TITLE
Photo testing better performance

### PR DESCRIPTION
**Pull request by GiovanniFurlan**
Strong speed up on text recognition, deleting the data saving on storage. 
Now the app saves the image path and the text on preferences, all preferences are related to the same manager "prefs" and default value are set on null.

### CODE REVIEW

**Review by PrandiniUniPD — APPROVED** [review]
The app is very fast and it seems to work well.

**Comment by PrandiniUniPD** [comment]
( This is a possible solution for the issue #22 )

**Review by lucamoroz — APPROVED** [review]
The app is faster on the text recognition but #12 is still a problem for me

**Comment by PrandiniUniPD** [comment]
The last push resolves the new conflicts generated by accepting the pull request #20 .
For an optimal performace is suggested to use AsyncTask to do in background the work of TextEctractor from the ResultActivity.

**Review by mattia1142866 — APPROVED** [review]

**Pull request merged**
