### PR TITLE
Rotation bug Resolved in CameraActivity, method imageOrientation ?

### PR DESCRIPTION
**Pull request by PrandiniUniPD**
This is a branch to solve the rotation bug reported in the issue #13 
Test it, it works for my device.

Filter the logs with the keyword "imageOrientation" for more details.

### CODE REVIEW

**Comment by lucamoroz** [comment]
The solution solved the bug for my Xiaomi mi6, but using a gyroscope may cause some problems when taking a picture with the phone barely parallel to the ground leading to a wrongly rotated image

**Comment by frankplus** [comment]
Seems to be working on Xiaomi mi a2 too.

**Comment by PrandiniUniPD** [comment]
In your opinion, could we accept this solution with the scope of a demo for tomorrow and eventually in the future implement the landscape mode and another way to resolve this bug?

**Comment by mattia1142866** [comment]
ho provato a fare la foto con il cellulare orientato in opposite landscape e si l'ha ruotata, ma di 90 gradi in più [Xiaomi mi A2 Lite]

**Comment by PrandiniUniPD** [comment]
> ho provato a fare la foto con il cellulare orientato in opposite landscape e si l'ha ruotata, ma di 90 gradi in più [Xiaomi mi A2 Lite]

What does the Log filtered by "imageOrientation" say?
Is it the case that has said @lucamoroz ?

> The solution solved the bug for my Xiaomi mi6, but using a gyroscope may cause some problems when taking a picture with the phone barely parallel to the ground leading to a wrongly rotated image

**Comment by PrandiniUniPD** [comment]
There is another solution for this bug, but we should implement and enable the landscape mode for this new one.
It consists to use the Surface orientations.
But I've some problem to change the camera preview. When I rotate the device from the portrait mode, the mode changes in landscape mode but the camera remains with the characteristics of the portrait mode with the difference that the dimension of the preview is stretched to fit the TextureView. 
Any ideas?

**Comment by mattia1142866** [comment]
i've search around internet and a lot of solutions are using the Inflaters. I think is a possible solution for change orientation of the screen and the elements that make up the layout

**Comment by mattia1142866** [comment]
This link talking about orientations using Camera2 API:
https://medium.com/@kenodoggy/solving-image-rotation-on-android-using-camera2-api-7b3ed3518ab6

**Pull request merged**
