### PR TITLE
Ingredients block recognizer

### LINKED ISSUE #18: The scanned text is not properly ordered
The lines of the scanned text is not always printed in the right order.
It often happen when the scanned text is fragmented in multiple lines not so condensed between them.

### PR DESCRIPTION
**Pull request by PrandiniUniPD**
This is a proposal of the app that focus the OCR processing to the block of the ingredients text.
This change can filter the text recognized automatically without a manual selection of the text by a human.
For my tests it also solve #18 .

### CODE REVIEW

**Comment by Fisher4537** [comment]
Tested on Api 21,
The screenshot was made a few minutes after running the program but the logs match with the screenshot.
screenshot_2018-11-23-11-58-46

```
11-23 11:54:20.485 14784-16690/unipd.se18.ocrcamera D/FA: Connected to remote service
11-23 11:54:20.485 14784-16690/unipd.se18.ocrcamera V/FA: Processing queued up service tasks: 4
11-23 11:54:20.746 14784-14784/unipd.se18.ocrcamera I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@27558402 time:81645175
11-23 11:54:21.026 14784-14784/unipd.se18.ocrcamera V/ActivityThread: updateVisibility : ActivityRecord{3d6d1314 token=android.os.BinderProxy@2104a51d {unipd.se18.ocrcamera/unipd.se18.ocrcamera.CameraActivity}} show : false
11-23 11:54:21.086 14784-14784/unipd.se18.ocrcamera V/TextExtractor: extractText -> onSuccess ->
    -----      RECOGNIZED TEXT       -----
    SUBITO ALLA CASS
    DI SPRECARE SCONTO
    Regi ina
    CIN
    sCEGLI QUANTO BASTA
    ESPRECHI DI MENO
    A CERTEZZA
    DI MENO.
    Regin
    A
    ape
    FOGLIO
    DI MANO
    ----- END OF THE RECOGNIZED TEXT -----
11-23 11:54:21.086 14784-16823/unipd.se18.ocrcamera I/TextExtractor: extractText -> text extracted in 733 milliseconds
11-23 11:54:21.086 14784-16823/unipd.se18.ocrcamera I/TextExtractor: getIngredientsBlock
11-23 11:54:21.136 14784-14784/unipd.se18.ocrcamera E/ViewRootImpl: sendUserActionEvent() mView == null
11-23 11:54:25.580 14784-16690/unipd.se18.ocrcamera V/FA: Inactivity, disconnecting from the service
11-23 11:54:26.221 14784-14784/unipd.se18.ocrcamera D/Sensor: P
11-23 11:54:26.221 14784-14784/unipd.se18.ocrcamera D/Sensor: P
11-23 11:54:26.411 14784-14784/unipd.se18.ocrcamera D/Sensor: P
11-23 11:54:26.411 14784-14784/unipd.se18.ocrcamera D/Sensor: P
11-23 11:54:26.441 14784-14784/unipd.se18.ocrcamera D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
11-23 11:54:26.581 14784-14784/unipd.se18.ocrcamera D/Sensor: P
```
Edit: Hope it is usefull

**Comment by PrandiniUniPD** [comment]
There aren't a block with ingredients there.

> Tested on Api 21,
> The screenshot was made a few minutes after running the program but the logs match with the screenshot.
> screenshot_2018-11-23-11-58-46
> 
> ```
> 11-23 11:54:20.485 14784-16690/unipd.se18.ocrcamera D/FA: Connected to remote service
> 11-23 11:54:20.485 14784-16690/unipd.se18.ocrcamera V/FA: Processing queued up service tasks: 4
> 11-23 11:54:20.746 14784-14784/unipd.se18.ocrcamera I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@27558402 time:81645175
> 11-23 11:54:21.026 14784-14784/unipd.se18.ocrcamera V/ActivityThread: updateVisibility : ActivityRecord{3d6d1314 token=android.os.BinderProxy@2104a51d {unipd.se18.ocrcamera/unipd.se18.ocrcamera.CameraActivity}} show : false
> 11-23 11:54:21.086 14784-14784/unipd.se18.ocrcamera V/TextExtractor: extractText -> onSuccess ->
>     -----      RECOGNIZED TEXT       -----
>     SUBITO ALLA CASS
>     DI SPRECARE SCONTO
>     Regi ina
>     CIN
>     sCEGLI QUANTO BASTA
>     ESPRECHI DI MENO
>     A CERTEZZA
>     DI MENO.
>     Regin
>     A
>     ape
>     FOGLIO
>     DI MANO
>     ----- END OF THE RECOGNIZED TEXT -----
> 11-23 11:54:21.086 14784-16823/unipd.se18.ocrcamera I/TextExtractor: extractText -> text extracted in 733 milliseconds
> 11-23 11:54:21.086 14784-16823/unipd.se18.ocrcamera I/TextExtractor: getIngredientsBlock
> 11-23 11:54:21.136 14784-14784/unipd.se18.ocrcamera E/ViewRootImpl: sendUserActionEvent() mView == null
> 11-23 11:54:25.580 14784-16690/unipd.se18.ocrcamera V/FA: Inactivity, disconnecting from the service
> 11-23 11:54:26.221 14784-14784/unipd.se18.ocrcamera D/Sensor: P
> 11-23 11:54:26.221 14784-14784/unipd.se18.ocrcamera D/Sensor: P
> 11-23 11:54:26.411 14784-14784/unipd.se18.ocrcamera D/Sensor: P
> 11-23 11:54:26.411 14784-14784/unipd.se18.ocrcamera D/Sensor: P
> 11-23 11:54:26.441 14784-14784/unipd.se18.ocrcamera D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
> 11-23 11:54:26.581 14784-14784/unipd.se18.ocrcamera D/Sensor: P
> ```

**Comment by PrandiniUniPD** [comment]
Actually the OCR find a block with the word "ingredients" on it and process only that block. You could see the code in TextExtractor.

**Comment by PrandiniUniPD** [comment]
For example, here we can see that the OCR has filtered the text and it has extracted only the block of the ingredients
photo_2018-11-23_12-07-53
photo_2018-11-23_12-08-02

**Comment by Fisher4537** [comment]
I tried on a product which has the string "INGREDIENTI" and It doesn't recognize the text. However the work is nice! We could keep two branch until we decide which is the best way to choose the ingredients. This is a key decision and we should evaluate which is the best! Maybe with UI tests. Btw nice work!

**Comment by PrandiniUniPD** [comment]
> I tried on a product which has the string "INGREDIENTI" and It doesn't recognize the text. However the work is nice! We could keep two branch until we decide which is the best way to choose the ingredients. This is a key decision and we should evaluate which is the best! Maybe with UI tests. Btw nice work!

The actual algorithm is trivial, but it's a demonstration that we can find an automatic version for recognizing only the block of the ingredients contained in a pics.
Precisely it find the block with "ingredients" (and only that block - a new algorithm based on the position of the block relatively to the "ingredients" word could be needed).

The word "ingredients" is an European standard to indicate the ingredients but a multiple language/standard recognition would be a new features that we could discuss about.

Thanks for your tests and comments, I'm agree with you of the fact we could continue to test and continue to improve an automatic version to recognize the block of the ingredients.

**Comment by PrandiniUniPD** [comment]
I've opened this pull request for proposing a work about an automatic method to recognize the block of the ingredients but for now my group and I will work on a manual version to focus the ingredients block.
So I close this pull request, we could work on it soon.

**Pull request closed without merging**
