### PR TITLE
Text extractor to string

### PR DESCRIPTION
**Pull request by PrandiniUniPD**
Proposal to a version of the class TextExtractor compatible with the OCRInterface (without observer).
That version return a String of the text recognized by the ocr.
Maybe this class not resolve the issue #18 and the other open issues.
Watch only the text extractor pieces of code.

### CODE REVIEW

**Review by frankplus — APPROVED** [review]
ok for me

**Comment by frankplus** [comment]
Does this resolve the rotated photo issue too?

**Comment by PrandiniUniPD** [comment]
> Does this resolve the rotated photo issue too?

This branch is derived from the branch used for solving that issue.
Now it uses the gyroscope for trying to solve that bug but in the pull request #16 there are more details than here, so for that bug we could refer to that pull request.

**Comment by lucamoroz** [comment]
Tested, seems good to me

**Review by lucamoroz — APPROVED** [review]
Tested and working

**Comment by GiovanniFurlan** [comment]
There is no "No text find, take new pic" so when no text is found there is white screen on text.

**Comment by PrandiniUniPD** [comment]
> There is no "No text find, take new pic" so when no text is found there is white screen on text.

Thank you, I've missed that feature. Now it is in the code.

**Review by GiovanniFurlan — APPROVED** [review]

**Comment by frankplus** [comment]
A downside of this change could be that parallelism between multiple ocr is not possible because of `while (!fbText.isSuccessful());`

**Review by stefanoromanello — APPROVED** [review]
ok

**Comment by PrandiniUniPD** [comment]
> A downside of this change could be that parallelism between multiple ocr is not possible because of `while (!fbText.isSuccessful());`

For parallelism could it work creating an instance of TextExtractor for every Thread that needs an ocr analyzing?

Anyway that statement is a problem because it isn't resource friendly.
I've tried with multiple thread and semaphores but not working properly, maybe i've missed something.
So I've put a ToDo there to indicate a required optimization.
Any ideas for substituting it with a resource friendly statement?

**Comment by PrandiniUniPD** [comment]
Four reviewers are agree to me for approving this pull request, the code of this pull request is useful for the tests we have to do for tomorrow and I've contacted @EliaBedin for speak about the usefully of this pull request and the inefficiency presents in this code (@EliaBedin and I have tested some alternatives).
So we can conclude that we can accept this pull request but we have to introduce a note that speak about the inefficiency, I'll put it in a new issue.

**Pull request merged**
